Repository Azure/vscode-aks-tools, pull requests merged in 2022-08, with the labels that each got.

#147 Publish 1.3.0.
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  resources/aks-startstop-cluster.png
Labels: Release 🧉🎷

#149 Publish 1.3.1.
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#150 Feature/redo extensionui start stop cluster
  package-lock.json
  package.json
  resources/webviews/aksclusterproperties/clusterproperties.html
  resources/webviews/common/detector.css
  src/azure-api-utils.ts
  src/commands/aksBestPractices/aksBestPractices.ts
  src/commands/aksCRUDDiagnostics/aksCRUDDiagnostics.ts
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/commands/aksCreateClusterNavToAzurePortal/aksCreateClusterNavToAzurePortal.ts
  src/commands/aksIdentitySecurity/aksIdentitySecurity.ts
  src/commands/aksKnownIssuesAvailabilityPerformance/aksKnownIssuesAvailabilityPerformance.ts
  src/commands/aksNavToPortal/aksNavToPortal.ts
  src/commands/aksNodeHealth/aksNodeHealth.ts
  src/commands/aksStarterWorkflow/configureStarterWorkflow.ts
  src/commands/azureServiceOperators/installAzureServiceOperator.ts
  src/commands/networkAndConnectivityDiagnostics/networkAndConnectivityDiagnostics.ts
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/periscope.ts
  src/commands/selectSubscriptions.ts
  src/commands/utils/clusters.ts
  src/commands/utils/detectors.ts
  src/commands/utils/webviews.ts
  src/extension.ts
  src/tree/aksClusterTreeItem.ts
  src/tree/azureAccountTreeItem.ts
  src/tree/subscriptionTreeItem.ts
  tsconfig.json
  tslint.json
  webpack.config.js
Labels: enhancement

#151 Publish 1.3.2
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#155 Feature/support usgovcloud endpoint
  src/commands/periscope/periscope.ts
Labels: bug

#154 publish 1.3.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#157 Update latest Periscope version and support optional Windows features
  package-lock.json
  package.json
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/models/clusterFeatures.ts
  src/commands/periscope/periscope.ts
  src/commands/utils/azurestorage.ts
  src/commands/utils/clusters.ts
Labels: enhancement

#156 Poll Starter Workflow: Remove comparison between 'seen' and latest templates
  .github/workflows/poll-starter-workflows.yml
Labels: bug, enhancement

#160 Add issue template for bugs and feature.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#161 Fix error when running Periscope using a branch release tag
  src/commands/periscope/helpers/periscopehelper.ts
Labels: enhancement

#162 Feature: Kubectl integration with vscode.
  package.json
  resources/webviews/aksKubectlCommand/akskubectlcommand.html
  src/commands/aksKubectlCommands/aksKubectlCommands.ts
  src/extension.ts
Labels: enhancement

#163 Publish 1.3.4
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  resources/right-click-menu-kubectl.png
Labels: Release 🧉🎷
