Repository Azure/vscode-aks-tools, pull requests merged in 2022-11, with the labels that each got.

#165 Generate periscope links from run ID
  package.json
  resources/webviews/periscope/failure.html
  resources/webviews/periscope/nodiagsetting.html
  resources/webviews/periscope/periscope.css
  resources/webviews/periscope/periscope.html
  resources/webviews/periscope/success.html
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/models/storage.ts
  src/commands/periscope/periscope.ts
  src/commands/utils/config.ts
Labels: enhancement

#167 Kubectl get events feature.
  package.json
  src/commands/aksKubectlCommands/aksKubectlCommands.ts
  src/extension.ts
Labels: enhancement

#168 Update ASO usage to latest.
  src/commands/azureServiceOperators/helpers/azureservicehelper.ts
Labels: enhancement

#169 Publish 1.3.5 changes.
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  resources/aks-periscope-webview.png
  resources/right-click-menu-kubectl.png
Labels: Release 🧉🎷

#170 Fix for css custom uri to use asWebViewURI.
  src/commands/aksBestPractices/aksBestPractices.ts
  src/commands/aksCRUDDiagnostics/aksCRUDDiagnostics.ts
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/commands/aksIdentitySecurity/aksIdentitySecurity.ts
  src/commands/aksKnownIssuesAvailabilityPerformance/aksKnownIssuesAvailabilityPerformance.ts
  src/commands/aksKubectlCommands/aksKubectlCommands.ts
  src/commands/aksNodeHealth/aksNodeHealth.ts
  src/commands/azureServiceOperators/helpers/azureservicehtmlhelper.ts
  src/commands/networkAndConnectivityDiagnostics/networkAndConnectivityDiagnostics.ts
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/periscope.ts
  src/commands/utils/webviews.ts
Labels: bug

#171 Changes for publishing 1.3.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#172 Vulnerability fix.
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#175 Download mechnism for kubelogin.
  package-lock.json
  package.json
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/commands/aksKubectlCommands/aksKubectlCommands.ts
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/models/config.ts
  src/commands/utils/config.ts
  src/commands/utils/dictionary.ts
  src/commands/utils/download/download.ts
  src/commands/utils/errorable.ts
  src/commands/utils/helper/kubeloginDownload.ts
  src/commands/utils/sleep.ts
  src/commands/utils/webviews.ts
Labels: enhancement

#176 Remove deprecating detector diagnostics for networkconnectivity.
  package.json
  resources/webviews/networkconnectivity/networkConnectivity.html
  src/commands/networkAndConnectivityDiagnostics/helpers/networkconnectivityhtmlhelper.ts
  src/commands/networkAndConnectivityDiagnostics/networkAndConnectivityDiagnostics.ts
  src/extension.ts
  src/tests/suite/networkconnecitivityhtmlhelpertest.test.ts
Labels: enhancement, Deprecating or retiring ☕️🤹

#177 Feature/add aks category connectivity detector
  .gitignore
  package.json
  src/commands/aksCategoryConnectivity/aksCategoryConnectivity.ts
  src/commands/utils/webviews.ts
  src/extension.ts
Labels: enhancement

#174 Supply access token to kubelogin to avoid interactive login
  package-lock.json
  package.json
  src/azure-api-utils.ts
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/commands/aksKubectlCommands/aksKubectlCommands.ts
  src/commands/aksNavToPortal/aksNavToPortal.ts
  src/commands/azureServiceOperators/helpers/azureservicehelper.ts
  src/commands/azureServiceOperators/installAzureServiceOperator.ts
  src/commands/periscope/periscope.ts
  src/commands/utils/authProvider.ts
  src/commands/utils/clusters.ts
  src/commands/utils/config.ts
  src/extension.ts
Labels: enhancement

#178 Publish 1.3.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷
