Repository Azure/vscode-aks-tools, pull requests merged in 2023-12, with the labels that each got.

#359 Update arm-authorization related changes.
  package-lock.json
  package.json
  src/commands/utils/azureAccount.ts
Labels: enhancement 🚀

#360 Remove incorrect use of isObject
  src/commands/utils/azureAccount.ts
Labels: bug, enhancement 🚀

#335 Create cluster ux
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/panels/CreateClusterPanel.ts
  src/panels/templates/DevTestCreateCluster.json
  src/panels/utilities/ClusterSpecCreationBuilder.ts
  src/webview-contract/webviewDefinitions/createCluster.ts
  webview-ui/src/CreateCluster/CreateCluster.module.css
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateCluster/CreateClusterPresetInput.tsx
  webview-ui/src/CreateCluster/CreateResourceGroup.tsx
  webview-ui/src/icons/DevTestIcon.tsx
  webview-ui/src/icons/svgProps.ts
  webview-ui/src/manualTest/createClusterTests.tsx
Labels: enhancement 🚀

#358 Move portal URL generation into a common function
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/commands/aksNavToPortal/aksNavToPortal.ts
  src/commands/detectors/detectors.ts
  src/commands/utils/detectors.ts
  src/commands/utils/env.ts
  src/panels/CreateClusterPanel.ts
  src/panels/DetectorPanel.ts
  src/webview-contract/webviewDefinitions/createCluster.ts
  src/webview-contract/webviewDefinitions/detector.ts
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/Success.tsx
  webview-ui/src/CreateCluster/helpers/state.ts
  webview-ui/src/Detector/Detector.tsx
  webview-ui/src/Detector/state.ts
  webview-ui/src/manualTest/createClusterTests.tsx
  webview-ui/src/manualTest/detectorTests.tsx
Labels: enhancement 🚀

#363 Feature: compare 2 aks cluster
  package.json
  src/commands/aksCompareCluster/aksCompareCluster.ts
  src/commands/utils/multiStepHelper.ts
  src/extension.ts
Labels: enhancement 🚀

#375 Add filters for TCPDump
  src/panels/TcpDumpPanel.ts
  src/webview-contract/webviewDefinitions/tcpDump.ts
  webview-ui/src/TCPDump/CaptureFilters.tsx
  webview-ui/src/TCPDump/TcpDump.module.css
  webview-ui/src/TCPDump/TcpDump.tsx
  webview-ui/src/TCPDump/filterScenarios/SpecificPodFilters.tsx
  webview-ui/src/TCPDump/filterScenarios/TwoPodsFilters.tsx
  webview-ui/src/TCPDump/protocols.ts
  webview-ui/src/TCPDump/state.ts
  webview-ui/src/TCPDump/state/captureNodeUpdate.ts
  webview-ui/src/TCPDump/state/dataLoading.ts
  webview-ui/src/TCPDump/state/nodeReferenceDataUpdate.ts
  webview-ui/src/TCPDump/state/referenceDataUpdate.ts
  webview-ui/src/TCPDump/state/scenarioFiltersUpdate.ts
  webview-ui/src/components/ResourceSelector.tsx
  webview-ui/src/manualTest/tcpDumpTests.tsx
  webview-ui/src/utilities/array.ts
Labels: enhancement 🚀

#378 Fix occasional error message that npm is missing
  .vscode/launch.json
  .vscode/tasks.json
Labels: enhancement 🚀

#380 Publish release 1.13.18
  CHANGELOG.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/aks-compare-cluster.md
  docs/book/src/features/features.md
  docs/book/src/features/tcp-dumps.md
  docs/book/src/resources/aks-compare-cluster-from.png
  docs/book/src/resources/aks-compare-cluster-result.png
  docs/book/src/resources/aks-compare-cluster-with.png
  docs/book/src/resources/create-cluster-webview-resource.png
  docs/book/src/resources/create-cluster-webview.png
  docs/book/src/resources/right-click-compare-cluster.png
  docs/book/src/resources/tcp-dump-filter-interface.png
  docs/book/src/resources/tcp-dump-filter-interface1.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#379 Use new telemetry library
  package-lock.json
  package.json
  src/commands/utils/reporter.ts
Labels: enhancement 🚀

#393 Refresh subscription
  package.json
  resources/dark/refresh.svg
  resources/light/refresh.svg
  src/commands/refreshSubscriptions.ts
  src/extension.ts
  src/tree/subscriptionTreeItem.ts
Labels: bug, enhancement 🚀

#405 Simplify webview dev task problem matcher
  .vscode/tasks.json
  webview-ui/.eslintrc.cjs
Labels: enhancement 🚀
