Repository Azure/vscode-aks-tools, pull requests merged in 2023-11, with the labels that each got.

#281 TCP Dump
  package.json
  src/commands/aksTCPCollection/tcpDumpCollection.ts
  src/commands/utils/kubectl.ts
  src/extension.ts
  src/panels/TcpDumpPanel.ts
  src/webview-contract/webviewDefinitions/tcpDump.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/InspektorGadget/NewTraceDialog.tsx
  webview-ui/src/TCPDump/TcpDump.module.css
  webview-ui/src/TCPDump/TcpDump.tsx
  webview-ui/src/TCPDump/state.ts
  webview-ui/src/components/NodeSelector.tsx
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/main.tsx
  webview-ui/src/manualTest/tcpDumpTests.tsx
Labels: enhancement 🚀

#285 Publish release 1.3.16.
  CHANGELOG.md
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/features.md
  docs/book/src/features/manage-cluster-operations.md
  docs/book/src/features/tcp-dumps.md
  docs/book/src/resources/aks-startstop-cluster.png
  docs/book/src/resources/right-click-menu-managedoperations.png
  docs/book/src/resources/right-click-tcp-dump-collect.png
  docs/book/src/resources/tcp-dump-linux-node.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#292 Feature: abort/reconcile cluster operation in show properties page.
  package-lock.json
  package.json
  src/commands/aksAbortLastOperation/aksAbortLastOperation.ts
  src/commands/utils/clusters.ts
  src/extension.ts
  src/panels/ClusterPropertiesPanel.ts
  src/webview-contract/webviewDefinitions/clusterProperties.ts
  webview-ui/src/ClusterProperties/ClusterDisplay.tsx
  webview-ui/src/ClusterProperties/state.ts
  webview-ui/src/manualTest/clusterPropertiesTests.tsx
Labels: enhancement 🚀

#297 fix the filePath as empty issue.
  src/panels/TcpDumpPanel.ts
Labels: bug

#334 Publish release 1.3.17.
  CHANGELOG.md
  docs/book/src/features/features.md
  docs/book/src/features/show-properties-azureportal-start-stop.md
  docs/book/src/resources/show-properties-abort.png
  docs/book/src/resources/show-properties-reconcile.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#346 fix dependabot types/node update.
  .github/workflows/build.yml
  .github/workflows/publish.yml
  package-lock.json
  package.json
  webview-ui/src/manualTest/inspektorGadgetTests.tsx
Labels: enhancement 🚀
