Repository Azure/vscode-aks-tools, pull requests merged in 2023-10, with the labels that each got.

#239 Fix comon id issue.
  package.json
  src/extension.ts
Labels: bug

#240 Update ASO version and move to webview-ui project
  resources/webviews/azureserviceoperator/azureserviceoperator.css
  resources/webviews/azureserviceoperator/azureserviceoperator.html
  resources/webviews/azureserviceoperator/result-section.html
  src/commands/azureServiceOperators/helpers/azureservicehelper.ts
  src/commands/azureServiceOperators/helpers/servicePrincipalHelper.ts
  src/commands/azureServiceOperators/installAzureServiceOperator.ts
  src/commands/utils/azureAccount.ts
  src/commands/utils/kubectl.ts
  src/commands/utils/tempfile.ts
  src/panels/AzureServiceOperatorPanel.ts
  src/webview-contract/webviewDefinitions/azureServiceOperator.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/AzureServiceOperator/AzureServiceOperator.module.css
  webview-ui/src/AzureServiceOperator/AzureServiceOperator.tsx
  webview-ui/src/AzureServiceOperator/Inputs.tsx
  webview-ui/src/AzureServiceOperator/Progress.tsx
  webview-ui/src/AzureServiceOperator/ProgressStep.tsx
  webview-ui/src/AzureServiceOperator/helpers/inputs.ts
  webview-ui/src/AzureServiceOperator/helpers/state.ts
  webview-ui/src/AzureServiceOperator/helpers/userCommands.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/asoTests.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀

#241 Implement Create Cluster as WebView
  package.json
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/multistep-helper/multistep-helper.ts
  src/panels/CreateClusterPanel.ts
  src/webview-contract/webviewDefinitions/createCluster.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/CreateCluster/CreateCluster.module.css
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateCluster/CreateResourceGroup.tsx
  webview-ui/src/CreateCluster/Success.tsx
  webview-ui/src/CreateCluster/helpers/state.ts
  webview-ui/src/CreateCluster/helpers/userCommands.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/createClusterTests.tsx
  webview-ui/src/manualTest/main.tsx
  webview-ui/src/utilities/validation.ts
Labels: enhancement 🚀

#243 Abort last operation on cluster.
  package-lock.json
  package.json
  src/commands/aksAbortLastOperation/aksAbortLastOperation.ts
  src/commands/utils/clusters.ts
  src/extension.ts
Labels: enhancement 🚀

#262 Publish 1.13.15
  CHANGELOG.md
  docs/book/src/features/features.md
  docs/book/src/features/k8s-api-health-points.md
  docs/book/src/features/manage-cluster-operations.md
  docs/book/src/features/run-kubectl-command.md
  docs/book/src/resources/azure-service-operator-screenshot.png
  docs/book/src/resources/create-cluster-webview.png
  docs/book/src/resources/kubectl-command-panel.png
  docs/book/src/resources/right-click-menu-kubectl.png
  docs/book/src/resources/right-click-menu-managedoperations.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#242 Download Draft Binaries PR.
  package.json
  src/commands/periscope/models/DraftConfig.ts
  src/commands/utils/config.ts
  src/commands/utils/helper/binaryDownloadHelper.ts
  src/commands/utils/helper/draftBinaryDownload.ts
  src/commands/utils/helper/kubectlGadgetDownload.ts
  src/commands/utils/helper/kubeloginDownload.ts
Labels: enhancement 🚀

#280 Feature/reconcile cluster using update
  package.json
  src/commands/aksReconcileCluster/aksReconcileCluster.ts
  src/commands/utils/clusters.ts
  src/extension.ts
Labels: enhancement 🚀

#279 Simplify state management for new webviews
  src/panels/AzureServiceOperatorPanel.ts
  src/panels/BasePanel.ts
  src/panels/CreateClusterPanel.ts
  src/panels/DetectorPanel.ts
  src/panels/InspektorGadgetPanel.ts
  src/panels/KubectlPanel.ts
  src/panels/PeriscopePanel.ts
  src/tests/suite/webview.test.ts
  src/webview-contract/messaging.ts
  webview-ui/src/AzureServiceOperator/AzureServiceOperator.tsx
  webview-ui/src/AzureServiceOperator/Inputs.tsx
  webview-ui/src/AzureServiceOperator/helpers/state.ts
  webview-ui/src/AzureServiceOperator/helpers/userCommands.ts
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateCluster/helpers/state.ts
  webview-ui/src/CreateCluster/helpers/userCommands.ts
  webview-ui/src/Detector/Detector.tsx
  webview-ui/src/Detector/state.ts
  webview-ui/src/InspektorGadget/InspektorGadget.tsx
  webview-ui/src/InspektorGadget/NewTraceDialog.tsx
  webview-ui/src/InspektorGadget/Overview.tsx
  webview-ui/src/InspektorGadget/ResourceSelector.tsx
  webview-ui/src/InspektorGadget/Traces.tsx
  webview-ui/src/InspektorGadget/helpers/state.ts
  webview-ui/src/InspektorGadget/helpers/userCommands.ts
  webview-ui/src/Kubectl/CommandOutput.tsx
  webview-ui/src/Kubectl/Kubectl.tsx
  webview-ui/src/Kubectl/helpers/state.ts
  webview-ui/src/Kubectl/helpers/userCommands.ts
  webview-ui/src/Periscope/Periscope.tsx
  webview-ui/src/Periscope/state.ts
  webview-ui/src/TestStyleViewer/TestStyleViewer.tsx
  webview-ui/src/TestStyleViewer/state.ts
  webview-ui/src/manualTest/TestScenarioSelector/TestScenarioSelector.tsx
  webview-ui/src/manualTest/asoTests.tsx
  webview-ui/src/manualTest/createClusterTests.tsx
  webview-ui/src/manualTest/detectorTests.tsx
  webview-ui/src/manualTest/inspektorGadgetTests.tsx
  webview-ui/src/manualTest/kubectlTests.tsx
  webview-ui/src/manualTest/main.tsx
  webview-ui/src/manualTest/periscopeTests.tsx
  webview-ui/src/manualTest/testStyleViewerTests.tsx
  webview-ui/src/utilities/manualTest.ts
  webview-ui/src/utilities/state.ts
  webview-ui/src/utilities/vscode.ts
Labels: enhancement 🚀

#282 Move Cluster Properties to webview project
  package-lock.json
  package.json
  resources/webviews/aksclusterproperties/clusterproperties.html
  resources/webviews/common/detector.css
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/commands/utils/clusters.ts
  src/commands/utils/webviews.ts
  src/panels/ClusterPropertiesPanel.ts
  src/webview-contract/webviewDefinitions/clusterProperties.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/ClusterProperties/AgentPoolDisplay.tsx
  webview-ui/src/ClusterProperties/ClusterDisplay.tsx
  webview-ui/src/ClusterProperties/ClusterProperties.module.css
  webview-ui/src/ClusterProperties/ClusterProperties.tsx
  webview-ui/src/ClusterProperties/state.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/clusterPropertiesTests.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀
