Repository Azure/vscode-aks-tools, pull requests merged in 2024-10, with the labels that each got.

#961 role assignments for automatic sku
  src/commands/utils/env.ts
  src/panels/CreateClusterPanel.ts
  src/panels/templates/AutomaticCreateCluster.json
  src/panels/utilities/ClusterSpecCreationBuilder.ts
Labels: enhancement 🚀

#946 Support creating automatic aks from GH Copilot
  package-lock.json
  package.json
  src/commands/aksAccount/aksAccount.ts
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts
  src/commands/utils/ghCopilotHandlers.ts
  src/commands/utils/subscriptions.ts
  src/extension.ts
  src/plugins/createAKS/createAKSClusterPlugin.ts
  src/plugins/getPlugins.ts
  src/plugins/shared/pluginResponses.ts
  src/types/aiazure/AiDriver.d.ts
  src/types/aiazure/AzureAgent.d.ts
  webview-ui/src/CreateCluster/CreateClusterPresetInput.tsx
Labels: enhancement 🚀

#948 Add cluster options util for GH Copilot scenarios
  src/assets.ts
  src/commands/utils/clusters.ts
  src/commands/utils/tempfile.ts
  src/plugins/shared/clusterOptions/options/selectExistingClusterOption.ts
  src/plugins/shared/clusterOptions/options/selectNewClusterOption.ts
  src/plugins/shared/clusterOptions/options/selectRecentClusterOption.ts
  src/plugins/shared/clusterOptions/selectClusterOptions.ts
  src/plugins/shared/clusterOptions/state/recentCluster.ts
  src/plugins/shared/types.ts
Labels: enhancement 🚀

#983 POC Update with correctly named subscription
  .github/workflows/poc.yml
Labels: POC (Proof of Concept)

#985 Removing POC, will keep locally
  .github/workflows/poc.yml
Labels: POC (Proof of Concept)

#960 Kubectl command generation plugin for GH Copilot
  package.json
  src/commands/aksOpenKubectlPanel/aksOpenKubectlPanel.ts
  src/extension.ts
  src/panels/KubectlPanel.ts
  src/plugins/getPlugins.ts
  src/plugins/kubectlGeneration/aksDocsRag/client.ts
  src/plugins/kubectlGeneration/aksDocsRag/constants.ts
  src/plugins/kubectlGeneration/generateKubectlCommandPlugin.ts
  src/plugins/shared/clusterOptions/options/selectExistingClusterOption.ts
  src/plugins/shared/pluginResponses.ts
  src/plugins/shared/types.ts
  src/webview-contract/webviewDefinitions/kubectl.ts
  webview-ui/src/Kubectl/Kubectl.tsx
  webview-ui/src/Kubectl/helpers/state.ts
  webview-ui/src/manualTest/kubectlTests.tsx
Labels: enhancement 🚀

#988 Kubectl savedialog UX changes
  webview-ui/src/Kubectl/Kubectl.module.css
Labels: bug

#986 Add deploy manifest handler for GH Copilot
  package.json
  src/commands/aksDeployManifest/aksDeployManifest.ts
  src/extension.ts
  src/plugins/deployManifest/deployManifestToAKSPlugin.ts
  src/plugins/getPlugins.ts
  src/plugins/shared/pluginResponses.ts
Labels: enhancement 🚀

#990 Revert "Kaito Deployment & UX Updates"
  package-lock.json
  package.json
  resources/kaitollmconfig/kaitollmconfig.json
  src/commands/aksKaito/aksKaito.ts
  src/commands/aksKaito/aksKaitoCreateCRD.ts
  src/commands/aksKaito/akskaitoGenerateYaml.ts
  src/commands/utils/configureWorkflowHelper.ts
  src/extension.ts
  src/panels/BasePanel.ts
  src/panels/KaitoModelsPanel.ts
  src/panels/KaitoPanel.ts
  src/webview-contract/webviewDefinitions/kaito.ts
  src/webview-contract/webviewDefinitions/kaitoModels.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/Kaito/Kaito.module.css
  webview-ui/src/Kaito/Kaito.tsx
  webview-ui/src/Kaito/KaitoModels.module.css
  webview-ui/src/Kaito/KaitoModels.tsx
  webview-ui/src/Kaito/state.ts
  webview-ui/src/icons/ArrowIcon.tsx
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/kaitoModelTests.tsx
  webview-ui/src/manualTest/kaitoTests.tsx
  webview-ui/src/manualTest/main.tsx
Labels: revert :repeat:

#1005 Improvements for GH copilot handlers
  src/auth/azureSessionProvider.ts
  src/auth/types.ts
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts
  src/commands/aksDeployManifest/aksDeployManifest.ts
  src/commands/aksOpenKubectlPanel/aksOpenKubectlPanel.ts
  src/panels/CreateClusterPanel.ts
  src/panels/KubectlPanel.ts
  src/plugins/kubectlGeneration/aksDocsRag/client.ts
  src/plugins/kubectlGeneration/aksDocsRag/constants.ts
  src/plugins/shared/clusterOptions/options/selectExistingClusterOption.ts
  src/plugins/shared/clusterOptions/selectClusterOptions.ts
  src/plugins/shared/pluginResponses.ts
  src/plugins/shared/telemetry/logger.ts
  src/plugins/shared/types.ts
Labels: enhancement 🚀, Change of behaviour

#1017 New Publish Workflow Fix
  .github/workflows/publish-v2.yml
Labels: enhancement 🚀, github_actions, POC (Proof of Concept)

#1003 Kaito additional error & quota handling
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/kaito-integration.md
  docs/book/src/resources/kaito-deploy-page.png
  docs/book/src/resources/kaito-install-page.png
  package-lock.json
  package.json
  src/commands/aksKaito/aksKaito.ts
  src/commands/aksKaito/aksKaitoCreateCRD.ts
  src/commands/aksKaito/akskaitoGenerateYaml.ts
  src/commands/utils/arm.ts
  src/panels/KaitoModelsPanel.ts
  src/panels/KaitoPanel.ts
  src/webview-contract/webviewDefinitions/kaito.ts
  src/webview-contract/webviewDefinitions/kaitoModels.ts
  webview-ui/src/Kaito/KaitoFamilyModelInput.tsx
  webview-ui/src/Kaito/state.ts
  webview-ui/src/KaitoModels/KaitoModels.module.css
  webview-ui/src/KaitoModels/KaitoModels.tsx
  webview-ui/src/KaitoModels/state.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/kaitoModelTests.tsx
Labels: enhancement 🚀

#1022 kaito needs to be KAITO named.
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  package.json
  src/commands/aksKaito/akskaitoGenerateYaml.ts
  src/panels/KaitoPanel.ts
  webview-ui/src/Kaito/Kaito.tsx
Labels: enhancement 🚀

#1023 Fix multiclick by disabling the button.
  src/panels/KaitoPanel.ts
  webview-ui/src/Kaito/Kaito.tsx
Labels: enhancement 🚀

#1021 Workflow modifications for official pipeline release
  .github/workflows/publish-v2.yml
Labels: enhancement 🚀, github_actions

#1024 Publish version 1.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1016 Add documentation for GH Copilot handlers and telemetry
  docs/book/src/SUMMARY.md
  docs/book/src/features/aks-plugins-github-copilot.md
  docs/book/src/resources/aks-gh-chat-create-cluster-1.png
  docs/book/src/resources/aks-gh-chat-deploy-manifest-1.png
  docs/book/src/resources/aks-gh-chat-kubectl-generation-1.png
  docs/book/src/telemetery.md
Labels: documentation 💾

#1025 Remove unused and unnecessary parameters for automatic cluster creation
  src/panels/templates/AutomaticCreateCluster.json
  src/panels/utilities/ClusterSpecCreationBuilder.ts
Labels: enhancement 🚀
