Repository Azure/vscode-aks-tools, pull requests merged in 2024-06, with the labels that each got.

#710 Update/pr size workflow with skip tag for necessary need.
  .github/workflows/restrict-pr-size.yml
Labels: enhancement 🚀, github_actions

#721 Release 1.4.6
  CHANGELOG.md
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/create-gh-workflow.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#695 AzureSessionProvider changes
  src/auth/azureSessionProvider.ts
  src/auth/types.ts
Labels: auth changes

#724 Avoid querying graph APIs for ASO
  package-lock.json
  package.json
  src/commands/azureServiceOperators/installAzureServiceOperator.ts
  src/commands/utils/azureAccount.ts
  src/panels/AzureServiceOperatorPanel.ts
Labels: bug

#750 Update vscode version.
  package-lock.json
  package.json
Labels: dependencies
