Repository Azure/vscode-aks-tools, pull requests merged in 2024-04, with the labels that each got.

#624 Day 0 - hook for Retina and Azure N/W Distributed Capture Scenarios with AKS VsCode Extension.
  package.json
  src/commands/aksRetinaCapture/aksRetinaCapture.ts
  src/commands/aksTCPCollection/tcpDumpCollection.ts
  src/commands/periscope/models/DraftConfig.ts
  src/commands/periscope/models/RetinaDownloadConfig.ts
  src/commands/utils/config.ts
  src/commands/utils/helper/retinaBinaryDownload.ts
  src/extension.ts
  src/panels/RetinaCapturePanel.ts
  src/panels/utilities/KubectlNetworkHelper.ts
  src/webview-contract/webviewDefinitions/retinaCapture.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/RetinaCapture/DeleteNodeExplorerDialog.tsx
  webview-ui/src/RetinaCapture/RetinaCapture.module.css
  webview-ui/src/RetinaCapture/RetinaCapture.tsx
  webview-ui/src/RetinaCapture/state.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/main.tsx
  webview-ui/src/manualTest/retinaCaptureTests.tsx
Labels: enhancement 🚀

#633 Publish release 1.4.3.
  CHANGELOG.md
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/features.md
  docs/book/src/features/inspektor-gadget.md
  docs/book/src/features/retina-capture.md
  docs/book/src/features/tcp-dumps.md
  docs/book/src/resources/retina-select-nodes.png
  docs/book/src/resources/retina-success-run-download.png
  docs/book/src/resources/right-click-retina-capture.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#636 Fix/build publish workflow
  .github/workflows/publish.yml
Labels: bug, github_actions

#551 Remove dependency on Azure Account extension
  package-lock.json
  package.json
  resources/azure.svg
  resources/azureSubscription.svg
  src/auth/azureAuth.ts
  src/auth/azureSessionProvider.ts
  src/auth/types.ts
  src/azure-api-utils.ts
  src/commands/aksAccount/aksAccount.ts
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/commands/aksCompareCluster/aksCompareCluster.ts
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/commands/aksDeleteCluster/aksDeleteCluster.ts
  src/commands/aksEraserTool/erasertool.ts
  src/commands/aksInspektorGadget/aksInspektorGadget.ts
  src/commands/aksKubectlCommands/aksKubectlCommands.ts
  src/commands/aksNavToPortal/aksNavToPortal.ts
  src/commands/aksReconcileCluster/aksReconcileCluster.ts
  src/commands/aksRetinaCapture/aksRetinaCapture.ts
  src/commands/aksRotateClusterCert/aksRotateClusterCert.ts
  src/commands/aksTCPCollection/tcpDumpCollection.ts
  src/commands/azureServiceOperators/installAzureServiceOperator.ts
  src/commands/detectors/detectors.ts
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/periscope.ts
  src/commands/selectSubscriptions.ts
  src/commands/utils/arm.ts
  src/commands/utils/authProvider.ts
  src/commands/utils/azureAccount.ts
  src/commands/utils/azureResources.ts
  src/commands/utils/clusters.ts
  src/commands/utils/config.ts
  src/commands/utils/detectors.ts
  src/commands/utils/resourceGroups.ts
  src/commands/utils/subscriptions.ts
  src/extension.ts
  src/panels/AzureServiceOperatorPanel.ts
  src/panels/ClusterPropertiesPanel.ts
  src/panels/CreateClusterPanel.ts
  src/tree/aksClusterTreeItem.ts
  src/tree/azureAccountTreeItem.ts
  src/tree/subscriptionTreeItem.ts
  webpack.config.js
Labels: enhancement 🚀

#642 Publish 1.4.4
  CHANGELOG.md
  docs/book/src/installation.md
  docs/book/src/resources/aks-signin.png
  docs/book/src/resources/aks-signinpopup.png
  docs/book/src/resources/aks-signintoaccountorswitchaccount.png
  package-lock.json
  package.json
Labels: Release 🧉🎷
