Repository Azure/vscode-aks-tools, pull requests merged in 2024-03, with the labels that each got.

#525 Upgrade the inspektor gadget to latest stable version.
  package.json
Labels: enhancement 🚀

#538 Feature/k8s version deprecated available
  src/commands/utils/clusters.ts
  src/panels/ClusterPropertiesPanel.ts
  src/webview-contract/webviewDefinitions/clusterProperties.ts
  webview-ui/src/ClusterProperties/ClusterDisplay.tsx
  webview-ui/src/manualTest/clusterPropertiesTests.tsx
Labels: enhancement 🚀

#567 Replace download with more in-house implementation.
  package-lock.json
  package.json
  src/commands/utils/download/download.ts
Labels: bug, enhancement 🚀

#570 Ensure file stream is closed after downloading
  src/commands/utils/download/download.ts
Labels: enhancement 🚀

#571 Remove unused workflow for this repo.
  .github/workflows/chatgpt-review.yml
Labels: enhancement 🚀

#573 Handle new archive structure for IG in windows
  src/commands/utils/helper/kubectlGadgetDownload.ts
Labels: bug

#572 Publish release 1.4.2
  CHANGELOG.md
  docs/book/src/features/show-properties-azureportal-start-stop.md
  docs/book/src/resources/show-properties-page-k8s-available-versions.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#574 Quality update: Update/workflow gh!!
  .github/workflows/publish.yml
  .github/workflows/website.yaml
Labels: enhancement 🚀

#576 Use @vscode/vsce for build workflow.
  .github/workflows/build.yml
  package-lock.json
  package.json
Labels: enhancement 🚀, dependencies

#575 Add Contributing standard for community standard at roots folder.
  CONTRIBUTING.md
Labels: enhancement 🚀, documentation 💾
