Repository Azure/vscode-aks-tools, pull requests merged in 2024-01, with the labels that each got.

#406 Make TreeItem implementation classes private
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/commands/aksCompareCluster/aksCompareCluster.ts
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/commands/aksCreateClusterNavToAzurePortal/aksCreateClusterNavToAzurePortal.ts
  src/commands/aksDeleteCluster/aksDeleteCluster.ts
  src/commands/aksNavToPortal/aksNavToPortal.ts
  src/commands/aksReconcileCluster/aksReconcileCluster.ts
  src/commands/aksRotateClusterCert/aksRotateClusterCert.ts
  src/commands/aksStarterWorkflow/configureStarterWorkflow.ts
  src/commands/detectors/detectors.ts
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/periscope.ts
  src/commands/refreshSubscriptions.ts
  src/commands/utils/azureAccount.ts
  src/commands/utils/clusters.ts
  src/commands/utils/detectors.ts
  src/extension.ts
  src/tree/aksClusterTreeItem.ts
  src/tree/azureAccountTreeItem.ts
  src/tree/subscriptionTreeItem.ts
Labels: enhancement 🚀

#415 Refresh subscriptions after adding and deleting clusters
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/commands/aksDeleteCluster/aksDeleteCluster.ts
  src/commands/utils/clusters.ts
  src/panels/CreateClusterPanel.ts
  src/tree/aksClusterTreeItem.ts
  src/tree/subscriptionTreeItem.ts
Labels: enhancement 🚀

#416 Add EraserTool deploy for cluster.
  package.json
  src/commands/aksEraserTool/erasertool.ts
  src/extension.ts
Labels: enhancement 🚀

#417 Publish year 2024 first release. 🎊🙏
  CHANGELOG.md
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/image-cleaner-eraser-tool.md
  docs/book/src/resources/right-click-run-eraser-1.png
  docs/book/src/resources/right-click-run-eraser.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#437 Add bestpractices progress badge.
  README.md
Labels: enhancement 🚀

#438 Add codeql analysis for repo.
  .github/workflows/codeql-analysis.yml
Labels: enhancement 🚀

#439 Add badge for codeql and chai test fix.
  README.md
  package-lock.json
  package.json
  src/tests/suite/deploystarterworkflow.test.ts
  src/tests/suite/webview.test.ts
Labels: enhancement 🚀, dependencies, investigating 🔍

#443 Changes in correlation with new GH Action Permission Changes.
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/website.yaml
Labels: enhancement 🚀

#442 Fix for making instance when cluster name is same but RG are different.
  src/commands/aksCompareCluster/aksCompareCluster.ts
  src/tree/aksClusterTreeItem.ts
Labels: bug

#451 Publish release 1.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#458 Remove duplcate lines.
  .github/dependabot.yml
Labels: enhancement 🚀, github_actions
