Repository Azure/vscode-aks-tools, pull requests merged in 2024-09, with the labels that each got.

#888 AKS diagnostic bug resolved & storage diagnostic added
  package.json
  src/commands/detectors/detectors.ts
  src/commands/utils/detectors.ts
  src/extension.ts
  webview-ui/src/Periscope/Periscope.tsx
Labels: bug, enhancement 🚀

#889 Release to publish 1.4.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#898 Minor bug fix for cluster properties panel
  webview-ui/src/ClusterProperties/ClusterProperties.module.css
Labels: bug

#911 update the engine with package.
  package-lock.json
  package.json
Labels: dependencies

#899 Feature enable KAITO Install and Workspace YAML generation.
  package-lock.json
  package.json
  resources/kaitollmconfig/kaitollmconfig.json
  resources/yaml/kaitoworkspace.yaml
  src/commands/aksKaito/aksKaito.ts
  src/commands/aksKaito/akskaitoGenerateYaml.ts
  src/commands/utils/arm.ts
  src/commands/utils/clusters.ts
  src/commands/utils/configureWorkflowHelper.ts
  src/extension.ts
  src/panels/BasePanel.ts
  src/panels/CreateClusterPanel.ts
  src/panels/KaitoPanel.ts
  src/webview-contract/webviewDefinitions/kaito.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/index.html
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/Kaito/Kaito.module.css
  webview-ui/src/Kaito/Kaito.tsx
  webview-ui/src/Kaito/KaitoFamilyModelInput.tsx
  webview-ui/src/Kaito/kaitoimage.png
  webview-ui/src/Kaito/state.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/kaitoTests.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀

#915 Add flags according to the need.
  .github/workflows/build.yml
Labels: enhancement 🚀, github_actions

#917 Update/gh workflows
  .github/workflows/build.yml
Labels: enhancement 🚀, github_actions

#913 Proper URL Sanitization
  src/tree/azureResourceNodeContributor.ts
Labels: auth changes

#914 Kaito fed creds and identity changes
  package-lock.json
  package.json
  src/commands/aksKaito/aksKaito.ts
  src/commands/utils/arm.ts
  src/commands/utils/clusters.ts
  src/commands/utils/managedServiceIdentity.ts
  src/commands/utils/roleAssignments.ts
  src/panels/AttachAcrToClusterPanel.ts
  src/panels/KaitoPanel.ts
  webview-ui/src/Kaito/Kaito.module.css
  webview-ui/src/Kaito/Kaito.tsx
  webview-ui/src/manualTest/kaitoTests.tsx
Labels: enhancement 🚀

#931 Fix for walkthrough and show welcome dependency.
  src/extension.ts
Labels: bug, enhancement 🚀

#945 Fixing freezing dockerfile create page
  src/panels/draft/DraftDockerfilePanel.ts
Labels: bug, enhancement 🚀

#932 Changes to publish 1.4.10.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#846 support create automatic aks cluster
  src/commands/aksCreateCluster/aksCreateCluster.ts
  src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts
  src/commands/utils/featureRegistrations.ts
  src/commands/utils/subscriptions.ts
  src/panels/CreateClusterPanel.ts
  src/panels/templates/AutomaticCreateCluster.json
  src/panels/utilities/ClusterSpecCreationBuilder.ts
  src/webview-contract/webviewDefinitions/createCluster.ts
  webview-ui/src/CreateCluster/CreateCluster.module.css
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateCluster/CreateClusterPresetInput.tsx
  webview-ui/src/icons/AutomaticIcon.tsx
Labels: enhancement 🚀
