Repository Azure/vscode-aks-tools, pull requests merged in 2024-05, with the labels that each got.

#676 Fix bump vscode 1.89 update.
  package-lock.json
  package.json
Labels: dependencies

#693 Release PR to publish 1.4.5
  CHANGELOG.md
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/draft-integration.md
  docs/book/src/resources/draft-command.png
  docs/book/src/resources/draft-deployment.png
  docs/book/src/resources/draft-dockerfile.png
  docs/book/src/resources/draft-dockerfile1.png
  docs/book/src/resources/draft-gh-workflow.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#698 Ensure initial selection values are populated
  webview-ui/src/Draft/DraftWorkflow/state.ts
  webview-ui/src/components/TextWithDropdown.tsx
  webview-ui/src/manualTest/draft/draftWorkflowTests.tsx
Labels: enhancement 🚀

#696 Add draft context menu commands and deprecate starter workflows
  package.json
  src/commands/draft/draftCommands.ts
  src/commands/draft/types.ts
  src/panels/draft/DraftDockerfilePanel.ts
Labels: enhancement 🚀, DRAFT tool integration 🤹‍♀️

#708 Initial commit for PR Size Check.
  .github/workflows/restrict-pr-size.yml
Labels: enhancement 🚀, github_actions
