Repository Azure/vscode-aks-tools, pull requests merged in 2024-11, with the labels that each got.

#1051 Track Version in the Extension Code, for walkthrough.
  src/extension.ts
Labels: bug, enhancement 🚀

#1053 Publish release 1.5.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1062 engine and vsce package update.
  package-lock.json
  package.json
Labels: dependencies

#1063 Publish release 1.5.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1047 kubectl-gadget: Update to v0.34.0
  package.json
Labels: enhancement 🚀

#1082 Remove activation event trigger.
  src/extension.ts
Labels: enhancement 🚀

#1095 Auto Deployments Utility Logic
  src/commands/utils/acrs.ts
  src/commands/utils/graph.ts
  src/commands/utils/roleAssignments.ts
Labels: enhancement 🚀
