Repository Azure/vscode-aks-tools, pull requests merged in 2024-07, with the labels that each got.

#773 Remove starter workflow traces as its removed now.
  .github/workflows/poll-starter-workflows.yml
  README.md
Labels: github_actions, documentation 💾

#775 Fix the code scanning.
  .github/workflows/restrict-pr-size.yml
Labels: dependencies, github_actions

#774 Release for version 1.4.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#798 Update vscode version and engine.
  package-lock.json
  package.json
Labels: dependencies

#814 Release version 1.4.8
  CHANGELOG.md
  docs/book/src/resources/show-properties-page-k8s-available-versions.png
  package-lock.json
  package.json
Labels: Release 🧉🎷

#815 U/X add border for the row.
  webview-ui/src/ClusterProperties/ClusterDisplayToolTip.tsx
  webview-ui/src/ClusterProperties/ClusterProperties.module.css
Labels: UX
