Repository Azure/vscode-aks-tools, pull requests merged in 2024-08, with the labels that each got.

#829 Adding flag to prevent draft from checking for manifests
  src/panels/draft/DraftDeploymentPanel.ts
Labels: bug

#857 Fix the vscode version with engine.
  package-lock.json
  package.json
Labels: dependencies

#832 Updated github auth scope to repo
  src/commands/draft/draftCommands.ts
Labels: bug, enhancement 🚀

#841 Fix the eslint no-unused-vars errors.
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/InspektorGadget/helpers/gadgets/profile.ts
  webview-ui/src/InspektorGadget/helpers/gadgets/snapshot.ts
  webview-ui/src/InspektorGadget/helpers/gadgets/top.ts
  webview-ui/src/InspektorGadget/helpers/gadgets/trace.ts
Labels: bug, enhancement 🚀, dependencies

#845 dependabot eslint plugin related changes.
  package-lock.json
  package.json
  src/auth/azureAuth.ts
  src/commands/draft/draftCommands.ts
  src/commands/utils/config.ts
  src/commands/utils/detectors.ts
  src/panels/InspektorGadgetPanel.ts
  src/webview-contract/webviewDefinitions/inspektorGadget.ts
  webview-ui/src/manualTest/inspektorGadgetTests.tsx
Labels: bug, dependencies

#859 possible fix.
  package-lock.json
  package.json
  src/tree/azureAccountTreeItem.ts
Labels: dependencies

#871 fix version to node-version
  .github/workflows/build.yml
Labels: bug

#844 Escaping special regex chars
  src/panels/TcpDumpPanel.ts
  src/tests/suite/TcpDumpPanel.test.ts
Labels: bug, enhancement 🚀

#874 changing draft version to .38 and removing manual appname
  package.json
  src/commands/utils/draft.ts
  src/panels/draft/DraftDeploymentPanel.ts
Labels: bug, enhancement 🚀
