Repository Azure/vscode-aks-tools, pull requests merged in 2024-12, with the labels that each got.

#1094 Fix the dependabot related issue.
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/InspektorGadget/TraceOutput.tsx
Labels: dependencies

#1107 Publish release 1.5.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1109 KAITO - Documentation Update
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/kaito-install-deploy.md
  docs/book/src/features/kaito-integration.md
  docs/book/src/features/kaito-manage-test.md
  docs/book/src/resources/kaito-deployment-example-in-progress.png
  docs/book/src/resources/kaito-deployment-example-success.png
  docs/book/src/resources/kaito-install-page.png
  docs/book/src/resources/kaito-installation-page.png
  docs/book/src/resources/kaito-installation-success.png
  docs/book/src/resources/kaito-manage-page.png
  docs/book/src/resources/kaito-test-page.png
  docs/book/src/resources/kaito-test-response.png
Labels: documentation 💾

#1120 add node os upgrade channel
  src/panels/templates/DevTestCreateCluster.json
Labels: bug, enhancement 🚀

#1121 Adding refresh option to cluster properties page
  src/panels/ClusterPropertiesPanel.ts
  src/webview-contract/webviewDefinitions/clusterProperties.ts
  webview-ui/src/ClusterProperties/ClusterProperties.module.css
  webview-ui/src/ClusterProperties/ClusterProperties.tsx
  webview-ui/src/ClusterProperties/state.ts
  webview-ui/src/manualTest/clusterPropertiesTests.tsx
Labels: enhancement 🚀

#1124 Publish release 1.5.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1123 Right Click Draft Validate
  package.json
  src/commands/draft/draftCommands.ts
  src/commands/draft/types.ts
  src/extension.ts
  src/panels/draft/DraftValidatePanel.ts
  src/webview-contract/webviewDefinitions/draft/draftValidate.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/Draft/DraftValidate/DraftValidate.tsx
  webview-ui/src/Draft/DraftValidate/state.ts
  webview-ui/src/Draft/index.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀, DRAFT tool integration 🤹‍♀️

#1145 Fix the vscode engine dependabot.
  package-lock.json
  package.json
Labels: dependencies
