Repository Azure/vscode-aks-tools, pull requests merged in 2025-02, with the labels that each got.

#1194 Create Fleet: UX Enhancement and Webview Testing
  package-lock.json
  package.json
  src/extension.ts
  src/panels/CreateFleetPanel.ts
  src/webview-contract/webviewDefinitions/createFleet.ts
  webview-ui/src/CreateFleet/CreateFleet.module.css
  webview-ui/src/CreateFleet/CreateFleet.tsx
  webview-ui/src/CreateFleet/CreateFleetInput.tsx
  webview-ui/src/CreateFleet/CreateFleetModeInput.tsx
  webview-ui/src/manualTest/createFleetTests.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀, Incremental Build 🏗️

#1221 update kubectl generation endpoint
  src/plugins/kubectlGeneration/aksDocsRag/constants.ts
Labels: enhancement 🚀

#1209 Automatic Cluster handling for KAITO installation
  src/panels/KaitoPanel.ts
  webview-ui/src/Kaito/Kaito.module.css
  webview-ui/src/Kaito/Kaito.tsx
Labels: Change of behaviour, Kaito

#1222 Beginning migration away from @vscode/webview-ui-toolkit/react package.
  webview-ui/src/Kaito/Kaito.tsx
  webview-ui/src/KaitoManage/KaitoManage.tsx
  webview-ui/src/KaitoModels/KaitoModels.tsx
  webview-ui/src/KaitoTest/KaitoTest.tsx
  webview-ui/src/main.css
Labels: enhancement 🚀, Deprecating or retiring ☕️🤹

#1228 Proper Devhub Callback Auth
  src/commands/devhub/aksAutomatedDeployments.ts
  src/extension.ts
  src/uriHandler.ts
Labels: enhancement 🚀, auth changes, Automated Deployments (DevHub)

#1240 Fix Cluster filter default behaviour
  src/commands/utils/clusterfilter.ts
  src/commands/utils/config.ts
Labels: bug, enhancement 🚀

#1238 [Backend] ACR Creation, App Registration Creation & Role Privileges
  src/panels/DevHubAutoDeployPanel.ts
  src/webview-contract/webviewDefinitions/automatedDeployments.ts
  webview-ui/src/AutomatedDeployments/state.ts
  webview-ui/src/manualTest/automatedDeploymentsTests.tsx
Labels: enhancement 🚀, Incremental Build 🏗️, Automated Deployments (DevHub)

#1241 [Backend] Getting GitHub File Tree
  src/commands/utils/octokitHelper.ts
  src/panels/DevHubAutoDeployPanel.ts
  src/webview-contract/webviewDefinitions/automatedDeployments.ts
  webview-ui/src/AutomatedDeployments/state.ts
  webview-ui/src/manualTest/automatedDeploymentsTests.tsx
Labels: Incremental Build 🏗️, Automated Deployments (DevHub)

#1244 Publish release 1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1242 Documentation: Create a Fleet
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/aks-fleet-manager.md
  docs/book/src/resources/aks-fleet-create-failure.png
  docs/book/src/resources/aks-fleet-create-input.png
  docs/book/src/resources/aks-fleet-create-right-click.png
  docs/book/src/resources/aks-fleet-create-success.png
Labels: documentation 💾

#1254 Treeview bug fix: showing members from different subscriptions
  src/tree/subscriptionTreeItem.ts
Labels: bug, enhancement 🚀

#1245 Show Fleet Properties
  package.json
  src/commands/aksFleetProperties/askFleetProperties.ts
  src/commands/utils/fleet.ts
  src/extension.ts
  src/panels/CreateFleetPanel.ts
  src/panels/FleetPropertiesPanel.ts
  src/tree/fleetTreeItem.ts
  src/webview-contract/webviewDefinitions/fleetProperties.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/FleetProperties/FleetProperties.tsx
  webview-ui/src/FleetProperties/state.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀

#1258 [Webview UI toolkit deprecation] Cluster & fleet create, cluster properties component removal
  webview-ui/src/ClusterProperties/AgentPoolDisplay.tsx
  webview-ui/src/ClusterProperties/ClusterDisplay.tsx
  webview-ui/src/ClusterProperties/ClusterDisplayToolTip.tsx
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateCluster/CreateResourceGroup.tsx
  webview-ui/src/CreateCluster/Success.tsx
  webview-ui/src/CreateFleet/CreateFleet.tsx
  webview-ui/src/CreateFleet/CreateFleetInput.tsx
  webview-ui/src/CreateFleet/CreateFleetModeInput.tsx
  webview-ui/src/main.css
Labels: enhancement 🚀, UX

#1277 Fix: Deploy button not appearing.
  package.json
  webview-ui/src/InspektorGadget/Overview.tsx
Labels: bug, enhancement 🚀
