Repository Azure/vscode-aks-tools, pull requests merged in 2025-03, with the labels that each got.

#1278 Update: Retina Binary to recent release.
  package.json
Labels: enhancement 🚀

#1280 Release v1.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1292 Fix npm warning for build.
  package-lock.json
  webview-ui/package-lock.json
Labels: bug

#1291 TCP Dump Bug Fix
  src/panels/TcpDumpPanel.ts
Labels: bug

#1260 [Webview UI toolkit deprecation] AttachAcrToCluster, DraftDeployment/Dockerfile/Workflow Panel component removal
  webview-ui/src/AttachAcrToCluster/AttachAcrToCluster.tsx
  webview-ui/src/AutomatedDeployments/AutomatedDeployments.tsx
  webview-ui/src/Draft/Draft.module.css
  webview-ui/src/Draft/DraftDeployment/DraftDeployment.tsx
  webview-ui/src/Draft/DraftDockerfile/DraftDockerfile.tsx
  webview-ui/src/Draft/DraftWorkflow/DraftWorkflow.tsx
  webview-ui/src/components/InlineAction.tsx
  webview-ui/src/components/TextWithDropdown.module.css
  webview-ui/src/components/TextWithDropdown.tsx
  webview-ui/src/main.css
  webview-ui/src/manualTest/components/FilePicker.module.css
  webview-ui/src/manualTest/components/FilePicker.tsx
Labels: Deprecating or retiring ☕️🤹

#1295 Quick Refactor: Moving DiagnosticSetting function to common place Cluster.ts.
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/periscope.ts
  src/commands/utils/clusters.ts
Labels: enhancement 🚀

#1259 [Webview UI toolkit deprecation] Inspektor Gadget, Retina Capture & TCP Dump component removal
  webview-ui/src/InspektorGadget/InspektorGadget.module.css
  webview-ui/src/InspektorGadget/InspektorGadget.tsx
  webview-ui/src/InspektorGadget/NewTraceDialog.tsx
  webview-ui/src/InspektorGadget/Overview.tsx
  webview-ui/src/InspektorGadget/ResourceSelector.tsx
  webview-ui/src/InspektorGadget/TraceItemSortSelector.tsx
  webview-ui/src/InspektorGadget/Traces.tsx
  webview-ui/src/RetinaCapture/DeleteNodeExplorerDialog.tsx
  webview-ui/src/RetinaCapture/RetinaCapture.tsx
  webview-ui/src/TCPDump/CaptureFilters.tsx
  webview-ui/src/TCPDump/TcpDump.module.css
  webview-ui/src/TCPDump/TcpDump.tsx
Labels: enhancement 🚀, UX

#1296 Upgrade Cluster Kubernetes Version
  src/commands/utils/clusters.ts
  src/panels/ClusterPropertiesPanel.ts
  src/webview-contract/webviewDefinitions/clusterProperties.ts
  webview-ui/src/ClusterProperties/ClusterDisplay.tsx
  webview-ui/src/ClusterProperties/ClusterDisplayToolTip.tsx
  webview-ui/src/ClusterProperties/ClusterProperties.module.css
  webview-ui/src/ClusterProperties/ClusterUpgrade.tsx
  webview-ui/src/ClusterProperties/ConfirmationDialog.tsx
  webview-ui/src/ClusterProperties/state.ts
  webview-ui/src/manualTest/clusterPropertiesTests.tsx
Labels: enhancement 🚀

#1261 [Webview UI toolkit deprecation] AzureServiceOperator, Detectors, Kubectl, & Periscope Panels component removal
  webview-ui/src/AzureServiceOperator/AzureServiceOperator.tsx
  webview-ui/src/AzureServiceOperator/Inputs.tsx
  webview-ui/src/Detector/Detector.tsx
  webview-ui/src/Kubectl/CommandInput.tsx
  webview-ui/src/Kubectl/Kubectl.tsx
  webview-ui/src/Kubectl/SaveCommandDialog.tsx
  webview-ui/src/Periscope/ErrorView.tsx
  webview-ui/src/Periscope/NodeActions.tsx
  webview-ui/src/Periscope/Periscope.tsx
  webview-ui/src/Periscope/SuccessView.tsx
Labels: enhancement 🚀, UX

#1306 Add upload logs feature for Retina Capture
  package.json
  src/commands/aksRetinaCapture/aksDownloadRetinaCapture.ts
  src/commands/aksRetinaCapture/aksUploadRetinaCapture.ts
  src/commands/aksRetinaCapture/utils.ts
  src/commands/periscope/helpers/periscopehelper.ts
  src/commands/periscope/periscope.ts
  src/commands/utils/azurestorage.ts
  src/commands/utils/clusters.ts
  src/extension.ts
  src/panels/RetinaCapturePanel.ts
  src/webview-contract/webviewDefinitions/retinaCapture.ts
  webview-ui/src/RetinaCapture/RetinaCapture.tsx
  webview-ui/src/manualTest/retinaCaptureTests.tsx
Labels: enhancement 🚀

#1276 Full replacement of VSCodeDropdown & VSCodeOption with custom react elements [Webview-UI-toolkit deprecation]
  webview-ui/src/AzureServiceOperator/Inputs.tsx
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateFleet/CreateFleetInput.tsx
  webview-ui/src/InspektorGadget/GadgetSelector.tsx
  webview-ui/src/InspektorGadget/Overview.tsx
  webview-ui/src/KaitoModels/KaitoModels.module.css
  webview-ui/src/TCPDump/CaptureFilters.tsx
  webview-ui/src/TCPDump/TcpDump.module.css
  webview-ui/src/TCPDump/filterScenarios/SpecificPodFilters.tsx
  webview-ui/src/TCPDump/filterScenarios/TwoPodsFilters.tsx
  webview-ui/src/components/CustomDropdown.module.css
  webview-ui/src/components/CustomDropdown.tsx
  webview-ui/src/components/CustomDropdownOption.tsx
  webview-ui/src/components/NodeSelector.tsx
  webview-ui/src/components/ResourceSelector.tsx
Labels: enhancement 🚀, Deprecating or retiring ☕️🤹
