Repository Azure/vscode-aks-tools, pull requests merged in 2025-01, with the labels that each got.

#1151 Publish version 1.5.5.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1160 Adding API calls to create a Fleet
  package-lock.json
  package.json
  src/commands/aksFleet/aksFleetManager.ts
  src/panels/CreateFleetPanel.ts
Labels: enhancement 🚀, Incremental Build 🏗️

#1122 Kaito Models - Code cleanup & memory/file handling improvements
  package.json
  src/commands/aksKaito/aksKaitoCreateCRD.ts
  src/commands/aksKaito/aksKaitoManage.ts
  src/commands/aksKaito/aksKaitoTest.ts
  src/commands/utils/kaitoValidationHelpers.ts
  src/panels/KaitoManagePanel.ts
  src/panels/KaitoModelsPanel.ts
  src/panels/KaitoTestPanel.ts
  src/panels/utilities/KaitoHelpers.ts
  src/webview-contract/webviewDefinitions/kaitoModels.ts
  webview-ui/src/KaitoModels/KaitoModels.tsx
  webview-ui/src/KaitoModels/state.ts
  webview-ui/src/manualTest/kaitoModelTests.tsx
Labels: Kaito

#1159 Fix the upgrade for eslint 9.17.0.
  eslint.config.mjs
  package-lock.json
  package.json
  webview-ui/eslint.config.mjs
  webview-ui/package-lock.json
  webview-ui/package.json
Labels: dependencies

#1164 Auto run Prettier-format.
  .pre-commit-config.yaml
  eslint.config.mjs
  src/auth/azureSessionProvider.ts
  src/commands/aksAccount/aksAccount.ts
  src/commands/utils/clusters.ts
  src/commands/utils/helper/retinaBinaryDownload.ts
  src/commands/utils/multiStepHelper.ts
  src/commands/utils/subscriptions.ts
  src/panels/RetinaCapturePanel.ts
  src/panels/utilities/KubectlNetworkHelper.ts
  src/plugins/deployManifest/deployManifestToAKSPlugin.ts
  src/plugins/getPlugins.ts
  src/plugins/kubectlGeneration/generateKubectlCommandPlugin.ts
  src/plugins/shared/clusterOptions/options/selectExistingClusterOption.ts
  src/plugins/shared/clusterOptions/options/selectNewClusterOption.ts
  src/tests/suite/webview.test.ts
  src/tree/azureAccountTreeItem.ts
  src/types/aiazure/AiDriver.d.ts
  src/types/aiazure/AzureAgent.d.ts
  src/webview-contract/webviewDefinitions/createCluster.ts
  webview-ui/eslint.config.mjs
  webview-ui/src/InspektorGadget/helpers/gadgets/profile.ts
  webview-ui/src/InspektorGadget/helpers/gadgets/snapshot.ts
  webview-ui/src/InspektorGadget/helpers/gadgets/top.ts
  webview-ui/src/InspektorGadget/helpers/gadgets/trace.ts
  webview-ui/src/Kubectl/helpers/state.ts
  webview-ui/src/RetinaCapture/DeleteNodeExplorerDialog.tsx
  webview-ui/src/RetinaCapture/RetinaCapture.module.css
  webview-ui/src/RetinaCapture/RetinaCapture.tsx
  webview-ui/src/RetinaCapture/state.ts
  webview-ui/src/icons/svgProps.ts
  webview-ui/src/manualTest/kubectlTests.tsx
  webview-ui/src/manualTest/retinaCaptureTests.tsx
Labels: enhancement 🚀

#1163 Add prettier format check.
  .github/workflows/format-check.yml
Labels: enhancement 🚀, github_actions

#1161 Create Fleet: panel implementation
  src/commands/utils/arm.ts
  src/panels/CreateFleetPanel.ts
  src/webview-contract/webviewDefinitions/createFleet.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀, UX

#1180 Add instruction for local vsix share.
  docs/book/src/development/development.md
Labels: enhancement 🚀, documentation 💾

#1181 Add prettier badge and development link.
  README.md
Labels: enhancement 🚀, documentation 💾

#1182 Update the build and publish badge.
  README.md
Labels: enhancement 🚀, github_actions, documentation 💾

#1179 Create Fleet: Full Cycle Completed
  src/commands/aksFleet/aksFleetManager.ts
  src/panels/CreateFleetPanel.ts
  webview-ui/src/CreateFleet/CreateFleet.tsx
  webview-ui/src/CreateFleet/CreateFleetInput.tsx
  webview-ui/src/CreateFleet/helpers/state.ts
  webview-ui/src/main.tsx
Labels: enhancement 🚀, UX

#1193 Initial Setup for Automated Deployments (Panel & Webview)
  package-lock.json
  package.json
  src/commands/devhub/aksAutomatedDeployments.ts
  src/commands/utils/acrs.ts
  src/extension.ts
  src/panels/DevHubAutoDeployPanel.ts
  src/tree/aksClusterTreeItem.ts
  src/webview-contract/webviewDefinitions/automatedDeployments.ts
  src/webview-contract/webviewTypes.ts
  webview-ui/src/AutomatedDeployments/AutomatedDeployments.module.css
  webview-ui/src/AutomatedDeployments/AutomatedDeployments.tsx
  webview-ui/src/AutomatedDeployments/state.ts
  webview-ui/src/main.tsx
  webview-ui/src/manualTest/automatedDeploymentsTests.tsx
  webview-ui/src/manualTest/main.tsx
Labels: enhancement 🚀, UX, Incremental Build 🏗️

#1196 Get Namespaces & Create Namespace Functionality [Backend]
  src/commands/devhub/aksAutomatedDeployments.ts
  src/commands/utils/clusters.ts
  src/panels/DevHubAutoDeployPanel.ts
  src/webview-contract/webviewDefinitions/automatedDeployments.ts
  webview-ui/src/AutomatedDeployments/state.ts
  webview-ui/src/manualTest/automatedDeploymentsTests.tsx
Labels: Incremental Build 🏗️, Automated Deployments (DevHub)

#1195 Git Repo & Branch Population for Automated Deployments [Backend]
  src/commands/utils/octokitHelper.ts
  src/panels/DevHubAutoDeployPanel.ts
  src/webview-contract/webviewDefinitions/automatedDeployments.ts
  webview-ui/src/AutomatedDeployments/AutomatedDeployments.tsx
  webview-ui/src/AutomatedDeployments/state.ts
  webview-ui/src/manualTest/automatedDeploymentsTests.tsx
Labels: Incremental Build 🏗️, Automated Deployments (DevHub)

#1208 Feature: Add Cluster Filtering in AKS VS Code Extension Tree Node
  package-lock.json
  package.json
  src/azure-api-utils.ts
  src/commands/utils/clusterfilter.ts
  src/commands/utils/clusters.ts
  src/commands/utils/config.ts
  src/extension.ts
  src/tree/azureAccountTreeItem.ts
  src/tree/subscriptionTreeItem.ts
Labels: enhancement 🚀
