Repository Azure/vscode-aks-tools, pull requests merged in 2025-06, with the labels that each got.

#1465 Updating supported models for v0.4.6 of KAITO
  l10n/bundle.l10n.json
  resources/kaitollmconfig/kaitollmconfig.json
  resources/yaml/kaitoworkspace.yaml
  src/commands/aksKaito/akskaitoGenerateYaml.ts
  webview-ui/src/KaitoModels/KaitoModels.tsx
Labels: Kaito

#1482 Safely bumping @azure/identity 4.6.0 to 4.10.1 with npm 'open' fix
  package-lock.json
  package.json
  src/panels/RetinaCapturePanel.ts
Labels: bug, dependencies

#1483 Publish release 1.6.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷
