Repository Azure/vscode-aks-tools, pull requests merged in 2025-04, with the labels that each got.

#1343 Changes to publish 1.6.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1334 Update Retina documentation
  docs/book/src/features/retina-capture.md
  docs/book/src/resources/retina-select-container.png
  docs/book/src/resources/retina-select-storage-account.png
  docs/book/src/resources/retina-success-check-storage-account.png
  docs/book/src/resources/retina-success-run-upload.png
  docs/book/src/resources/right-click-download-retina-capture.png
  docs/book/src/resources/right-click-upload-retina-capture.png
Labels: documentation 💾

#1345 Reverting @azure/identity update to fix issues in non-wsl Windows
  package-lock.json
  package.json
Labels: bug

#1346 Publish release 1.6.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1330 Complete removal of webview-ui-toolkit package & elements
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/AzureServiceOperator/ProgressStep.tsx
  webview-ui/src/ClusterProperties/ClusterProperties.module.css
  webview-ui/src/ClusterProperties/ClusterProperties.tsx
  webview-ui/src/ClusterProperties/ClusterUpgrade.tsx
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateFleet/CreateFleet.tsx
  webview-ui/src/FleetProperties/FleetProperties.tsx
  webview-ui/src/InspektorGadget/InspektorGadget.module.css
  webview-ui/src/InspektorGadget/InspektorGadget.tsx
  webview-ui/src/InspektorGadget/NewTraceDialog.tsx
  webview-ui/src/InspektorGadget/Overview.tsx
  webview-ui/src/InspektorGadget/ResourceSelector.tsx
  webview-ui/src/InspektorGadget/TraceOutput.tsx
  webview-ui/src/Kaito/Kaito.tsx
  webview-ui/src/KaitoManage/KaitoManage.tsx
  webview-ui/src/KaitoModels/KaitoModels.tsx
  webview-ui/src/Kubectl/CommandOutput.tsx
  webview-ui/src/Periscope/SuccessView.tsx
  webview-ui/src/RetinaCapture/RetinaCapture.module.css
  webview-ui/src/RetinaCapture/RetinaCapture.tsx
  webview-ui/src/TCPDump/TcpDump.tsx
  webview-ui/src/components/ProgressRing.module.css
  webview-ui/src/components/ProgressRing.tsx
  webview-ui/src/components/ResourceSelector.tsx
  webview-ui/src/components/TextWithDropdown.tsx
Labels: Deprecating or retiring ☕️🤹, UX

#1331 Updating Documentation with Custom elements section
  docs/book/src/development/webview-development.md
Labels: documentation 💾

#1349 Fix for viewing downloaded files when using WSL
  src/panels/RetinaCapturePanel.ts
  src/panels/TcpDumpPanel.ts
Labels: bug, enhancement 🚀

#1307 Fix for similarly named clusters showing in adjacent subscription nodes
  src/commands/utils/clusterfilter.ts
  src/commands/utils/config.ts
  src/tree/fleetTreeItem.ts
  src/tree/subscriptionTreeItem.ts
Labels: bug, Change of behaviour

#1348 Update/detector upgrade sceanrio
  src/commands/aksClusterProperties/aksClusterProperties.ts
  src/panels/ClusterPropertiesPanel.ts
  src/webview-contract/webviewDefinitions/clusterProperties.ts
  webview-ui/src/ClusterProperties/ClusterUpgrade.tsx
  webview-ui/src/ClusterProperties/state.ts
  webview-ui/src/manualTest/clusterPropertiesTests.tsx
Labels: enhancement 🚀

#1364 Update retina doc with steps
  docs/book/src/features/retina-capture.md
Labels: enhancement 🚀, documentation 💾

#1368 Publish release 1.6.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1319 [Kaito] Fix for v4 node pool deletion issue
  src/commands/aksKaito/aksKaitoManage.ts
  src/panels/KaitoManagePanel.ts
Labels: Change of behaviour, Kaito

#1318 KAITO v4.4 support
  resources/kaitollmconfig/kaitollmconfig.json
  src/commands/aksKaito/aksKaitoManage.ts
  src/commands/aksKaito/akskaitoGenerateYaml.ts
  src/commands/utils/clusters.ts
  src/commands/utils/kaitoValidationHelpers.ts
  src/panels/KaitoManagePanel.ts
  src/panels/KaitoPanel.ts
  src/panels/KaitoTestPanel.ts
  src/panels/utilities/KaitoHelpers.ts
  webview-ui/src/KaitoManage/KaitoManage.tsx
  webview-ui/src/KaitoModels/KaitoModels.tsx
Labels: Kaito

#1381 Publish release 1.6.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷
