Repository Azure/vscode-aks-tools, pull requests merged in 2025-05, with the labels that each got.

#1408 Add the enable copilot flag for gh copilot feature scenario.
  package.json
  src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts
  src/commands/aksDeployManifest/aksDeployManifest.ts
  src/commands/aksOpenKubectlPanel/aksOpenKubectlPanel.ts
  src/commands/utils/config.ts
Labels: enhancement 🚀

#1410 Publish release 1.6.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1409 Documentation for the copilot flag.
  docs/book/src/features/aks-plugins-github-copilot.md
Labels: documentation 💾

#1411 Fix messaging to add link to the doc.
  src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts
  src/commands/aksDeployManifest/aksDeployManifest.ts
  src/commands/aksOpenKubectlPanel/aksOpenKubectlPanel.ts
  src/commands/utils/clusters.ts
Labels: enhancement 🚀

#1412 Update vsc pacakge and engine.
  package-lock.json
  package.json
Labels: dependencies

#1427 Fix the runner break as the version is deprecated.
  .github/workflows/website.yaml
Labels: bug, enhancement 🚀

#1428 Publish release 1.6.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1438 Fix for catering security alerts and permissions.
  .github/workflows/format-check.yml
Labels: enhancement 🚀, dependencies

#1429 Setting up localization
  l10n/bundle.l10n.json
  package-lock.json
  package.json
  package.nls.json
  src/extension.ts
  src/panels/AttachAcrToClusterPanel.ts
  src/panels/AzureServiceOperatorPanel.ts
  src/panels/BasePanel.ts
  src/panels/ClusterPropertiesPanel.ts
  src/panels/CreateClusterPanel.ts
  src/panels/CreateFleetPanel.ts
  src/panels/DetectorPanel.ts
  src/panels/DevHubAutoDeployPanel.ts
  src/panels/FleetPropertiesPanel.ts
  src/panels/InspektorGadgetPanel.ts
  src/panels/KaitoManagePanel.ts
  src/panels/KaitoModelsPanel.ts
  src/panels/KaitoPanel.ts
  src/panels/KaitoTestPanel.ts
  src/panels/KubectlPanel.ts
  src/panels/RetinaCapturePanel.ts
  src/panels/TcpDumpPanel.ts
  src/panels/draft/DraftDeploymentPanel.ts
  src/panels/draft/DraftDockerfilePanel.ts
  src/panels/draft/DraftValidatePanel.ts
  src/panels/draft/DraftWorkflowPanel.ts
  src/tree/azureAccountTreeItem.ts
  webview-ui/src/AttachAcrToCluster/AttachAcrToCluster.tsx
  webview-ui/src/ClusterProperties/AgentPoolDisplay.tsx
  webview-ui/src/ClusterProperties/ClusterDisplay.tsx
  webview-ui/src/ClusterProperties/ClusterProperties.tsx
  webview-ui/src/ClusterProperties/ClusterUpgrade.tsx
  webview-ui/src/CreateCluster/CreateCluster.module.css
  webview-ui/src/CreateCluster/CreateCluster.tsx
  webview-ui/src/CreateCluster/CreateClusterInput.tsx
  webview-ui/src/CreateCluster/CreateClusterPresetInput.tsx
  webview-ui/src/CreateCluster/CreateResourceGroup.tsx
  webview-ui/src/CreateFleet/CreateFleet.module.css
  webview-ui/src/CreateFleet/CreateFleet.tsx
  webview-ui/src/CreateFleet/CreateFleetInput.tsx
  webview-ui/src/CreateFleet/CreateFleetModeInput.tsx
  webview-ui/src/Draft/DraftDeployment/DraftDeployment.tsx
  webview-ui/src/Draft/DraftWorkflow/DraftWorkflow.tsx
  webview-ui/src/FleetProperties/FleetProperties.tsx
  webview-ui/src/InspektorGadget/InspektorGadget.tsx
  webview-ui/src/InspektorGadget/NewTraceDialog.tsx
  webview-ui/src/Kaito/Kaito.tsx
  webview-ui/src/KaitoManage/KaitoManage.tsx
  webview-ui/src/KaitoModels/KaitoModels.tsx
  webview-ui/src/KaitoTest/KaitoTest.tsx
  webview-ui/src/Kubectl/CommandList.tsx
  webview-ui/src/Kubectl/Kubectl.tsx
  webview-ui/src/RetinaCapture/RetinaCapture.tsx
  webview-ui/src/TCPDump/TcpDump.tsx
  webview-ui/src/components/ResourceSelector.tsx
  webview-ui/src/main.css
  webview-ui/src/main.tsx
  webview-ui/src/utilities/vscode.ts
Labels: enhancement 🚀

#1444 Adding namespace awareness & different runtime support for KAITO models
  src/commands/aksKaito/aksKaitoManage.ts
  src/commands/aksKaito/aksKaitoTest.ts
  src/panels/KaitoManagePanel.ts
  src/panels/KaitoModelsPanel.ts
  src/panels/KaitoTestPanel.ts
  src/panels/utilities/KaitoHelpers.ts
  src/webview-contract/webviewDefinitions/kaitoManage.ts
  src/webview-contract/webviewDefinitions/kaitoModels.ts
  webview-ui/src/KaitoManage/KaitoManage.tsx
  webview-ui/src/KaitoModels/KaitoModels.tsx
  webview-ui/src/manualTest/kaitoManageTests.tsx
Labels: Change of behaviour, Kaito
