Repository Azure/vscode-aks-tools, pull requests merged in 2025-08, with the labels that each got.

#1525 Added option to port-forward KAITO workspace service
  src/panels/KaitoManagePanel.ts
  src/webview-contract/webviewDefinitions/kaitoManage.ts
  webview-ui/src/KaitoManage/KaitoManage.tsx
  webview-ui/src/KaitoManage/state.ts
  webview-ui/src/manualTest/kaitoManageTests.tsx
Labels: Kaito

#1524 Add AKS MCP Server using AKS Ext level command.
  package.json
  src/commands/aksMCP/aksMCPServer.ts
  src/commands/periscope/models/aksMCPServerConfig.ts
  src/commands/utils/config.ts
  src/commands/utils/helper/mcpServerDownloadHelper.ts
  src/extension.ts
Labels: enhancement 🚀

#1526 Windows binary release for win arch is specific format.
  src/commands/utils/helper/mcpServerDownloadHelper.ts
Labels: bug, enhancement 🚀

#1528 Publish release 1.6.12
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1527 Add documentation for AKS MCP Server.
  docs/book/src/README.md
  docs/book/src/SUMMARY.md
  docs/book/src/features/aks-mcp-server-integration.md
  docs/book/src/resources/aks-mcp-server-command.png
  docs/book/src/resources/aks-mcp-server-ghc-configure.png
  docs/book/src/resources/aks-mcp-server-ghc-list.png
  docs/book/src/resources/aks-mcp-server-list-running.png
  docs/book/src/resources/aks-mcp-server-list.png
  docs/book/src/resources/aks-mcp-server-success.png
Labels: documentation 💾

#1543 Update arm-resoruce and type-node package and related changes.
  package-lock.json
  package.json
  src/commands/utils/helper/draftBinaryDownload.ts
  src/commands/utils/helper/kubectlGadgetDownload.ts
  src/commands/utils/helper/kubeloginDownload.ts
  src/commands/utils/helper/mcpServerDownloadHelper.ts
  src/commands/utils/helper/retinaBinaryDownload.ts
  src/panels/CreateClusterPanel.ts
  src/panels/utilities/ClusterSpecCreationBuilder.ts
  webview-ui/package-lock.json
Labels: dependencies

#1564 Fix the client using sessionProvider instead of default.
  src/commands/aksRetinaCapture/aksUploadRetinaCapture.ts
  src/commands/utils/azurestorage.ts
Labels: enhancement 🚀
