Repository Azure/vscode-aks-tools, pull requests merged in 2025-07, with the labels that each got.

#1466 IG menu restructure: Investigate DNS and Real-time TCP Monitoring
  package.json
  package.nls.json
  src/commands/aksInspektorGadget/aksDnsTrace.ts
  src/commands/aksInspektorGadget/aksTcpTrace.ts
  src/commands/aksInspektorGadget/clusterOperations.ts
  src/commands/aksInspektorGadget/inspektorGadgetHelper.ts
  src/extension.ts
  src/panels/InspektorGadgetPanel.ts
  src/webview-contract/webviewDefinitions/inspektorGadget.ts
  webview-ui/src/InspektorGadget/GadgetSelector.tsx
  webview-ui/src/InspektorGadget/InspektorGadget.tsx
  webview-ui/src/InspektorGadget/NewTraceDialog.tsx
  webview-ui/src/InspektorGadget/Overview.tsx
  webview-ui/src/InspektorGadget/Traces.tsx
  webview-ui/src/InspektorGadget/helpers/state.ts
  webview-ui/src/components/NodeSelector.tsx
Labels: enhancement 🚀

#1501 Fix telemetery update failure.
  package-lock.json
  package.json
  src/commands/utils/reporter.ts
Labels: dependencies

#1502 Fix vsc update.
  package-lock.json
  package.json
Labels: dependencies

#1523 Publish release 1.6.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release 🧉🎷

#1522 Update Inspektor Gadget doc
  docs/book/src/features/features.md
  docs/book/src/features/inspektor-gadget.md
  docs/book/src/resources/ig-deploy-prompt.png
  docs/book/src/resources/ig-gadget-dialog.png
  docs/book/src/resources/ig-improve-security.png
  docs/book/src/resources/ig-investigate-block-io.png
  docs/book/src/resources/ig-resource-utilization-troubleshooting.png
  docs/book/src/resources/inspector-gadget-dns.png
  docs/book/src/resources/inspector-gadget-main-menu.png
  docs/book/src/resources/inspector-gadget-tcp.png
  docs/book/src/resources/right-click-inspektor-gadget.png
Labels: documentation 💾
